# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:

  # Path to dist folder
  dist: "app/build/"

  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "src/sass/app.scss"

  # Paths to JavaScript libraries, which are combined into one file
  javascript:
  ## Core Sophia files
  - "src/js/core/namespace.js"
  - "src/js/core/config-default.js"
  - "src/js/core/windowmanager.js"
  - "src/js/core/windowapp.js"
  - "src/js/core/startup.js"

  ## Libraries
  - "src/js/lib/xregexp.js"
  - "src/js/lib/clipboard.js"
  - "src/js/lib/i18next.js"
  - "src/js/lib/jsdiff.js"

  ## Translations
  ### If you aren't using a translation, just remove it's line from the list
  - "src/js/resources/en.js"
  - "src/js/resources/fr.js"
  - "src/js/resources/de.js"
  - "src/js/resources/es.js"
  - "src/js/resources/ru.js"
  - "src/js/resources/hi.js"
  - "src/js/resources/ar.js"
  - "src/js/resources/af.js"
  - "src/js/resources/bn.js"
  - "src/js/resources/id.js"
  - "src/js/resources/sw.js"
  - "src/js/resources/tr.js"
  - "src/js/resources/ja.js"
  - "src/js/resources/zh-CN.js"
  - "src/js/resources/zh-TW.js"

  ### Common js files
  - "src/js/common/languagedata.js"
  - "src/js/common/countriesdata.js"
  - "src/js/common/ajax.js"
  - "src/js/common/appsettings.js"
  - "src/js/common/eventlistener.js"
  - "src/js/common/timer.js"
  - "src/js/common/stringutility.js"
  - "src/js/common/detection.js"
  - "src/js/common/navigation.js"
  - "src/js/common/iso2iana.js"
  - "src/js/common/clickoff.js"

  ### Bible js files
  - "src/js/bible/bible.data.js"
  - "src/js/bible/bible.reference.js"
  - "src/js/bible/morphology.js"

  ### Texts js files
  - "src/js/texts/textloader.js"
  - "src/js/texts/textprovider-local.js"
  - "src/js/texts/textprovider-fcbh.js"
  - "src/js/texts/textprovider-abs.js"
  - "src/js/texts/search.js"

  ### Media js files
  - "src/js/media/audiodatamanager.js"
  - "src/js/media/jesusfilmapi.js"
  - "src/js/media/medialibrary.js"

  ### UI js files
  - "src/js/ui/textchooser.js"
  - "src/js/ui/textnavigator.js"
  - "src/js/ui/infowindow.js"
  - "src/js/ui/movablewindow.js"

  ### Plugin js files
  - "src/js/plugins/lemmainfo.js"
  - "src/js/plugins/lemmamatch.js"
  - "src/js/plugins/lemmapopup.js"
  - "src/js/plugins/versematch.js"
  - "src/js/plugins/eng2p.js"
  - "src/js/plugins/visualfilters.js"
  - "src/js/plugins/crossreferences.js"
  - "src/js/plugins/notes.js"
  - "src/js/plugins/googleanalytics.js"
  - "src/js/plugins/mediaplugin.js"

  ### Window js files
  - "src/js/windows/textwindow.js"
  - "src/js/windows/searchwindow.js"
  - "src/js/windows/mapswindow.js"
  - "src/js/windows/mediawindow.js"
  - "src/js/windows/parallelswindow.js"
  - "src/js/windows/scroller.js"
  - "src/js/windows/scrolleraudio.js"
  - "src/js/windows/textcomparisonwindow.js"
  - "src/js/windows/audiowindow.js"
  - "src/js/windows/statisticswindow.js"
  - "src/js/windows/deafbiblewindow.js"

  ### Menu js files
  - "src/js/menu/mainmenu.js"
  - "src/js/menu/topsearch.js"
  - "src/js/menu/fullscreen.js"
  - "src/js/menu/addwindow.js"
  - "src/js/menu/config.js"
  - "src/js/menu/about.js"
  - "src/js/menu/feedback.js"
  - "src/js/menu/navigation.js"
  - "src/js/menu/config-fontsize.js"
  - "src/js/menu/config-fontfamily.js"
  - "src/js/menu/config-theme.js"
  - "src/js/menu/config-language.js"
  - "src/js/menu/config-toggles.js"
  - "src/js/menu/config-url.js"